school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('admin/',include(('customadmin.urls','customadmin'),namespace='customadmin')),
    path('web/',include(('website.urls','website'),namespace='web')),
    path('',include(('website2.urls','website2'),namespace='web2')),
    path('user/',include(('users.urls','user'),namespace='user')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.loginPage, name='login'),
    path('logout/',views.logout_view,name='logout'),

]

website/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('about',views.about,name='aboutus'),
    path('contact',views.contact,name='contact'),
    path('gallery',views.gallery,name='gallery'),
    path('addmission',views.addmission,name='addmission1'),
]

templates/web/contactus.html
{% extends "web/basic.html" %}
{% load static %}
{% block style %}

{% endblock %}
{% block content %}

        <!-- breadcrumb -->
        <div class="site-breadcrumb" style="background: url({% static 'school/images/01.jpg' %})">
            <div class="container">
                <h2 class="breadcrumb-title">Contact Us</h2>
                <ul class="breadcrumb-menu">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Contact Us</li>
                </ul>
            </div>
        </div>
        <!-- breadcrumb end -->


        <!-- contact area -->
        <div class="contact-area py-120">
            <div class="container">
                <div class="contact-content">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="contact-info">
                                <div class="contact-info-icon">
                                    <i class="fal fa-map-location-dot"></i>
                                </div>
                                <div class="contact-info-content">
                                    <h5>Office Address</h5>
                                    <p>226/2, Firoz gandhi colony, phase 2, Near sector 9 petrol pump, Gurugram (HR)-12201</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="contact-info">
                                <div class="contact-info-icon">
                                    <i class="fal fa-phone-volume"></i>
                                </div>
                                <div class="contact-info-content">
                                    <h5>Call Us</h5>
                                    <p>+91 7011948893</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="contact-info">
                                <div class="contact-info-icon">
                                    <i class="fal fa-envelopes"></i>
                                </div>
                                <div class="contact-info-content">
                                    <h5>Email Us</h5>
                                    <p><a href="mailto:Littlestarpre03@gmail.com" class="__cf_email__" >Littlestarpre03@gmail.com</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="contact-info">
                                <div class="contact-info-icon">
                                    <i class="fal fa-alarm-clock"></i>
                                </div>
                                <div class="contact-info-content">
                                    <h5>Open Time</h5>
                                    <p>Mon - Sat (8.00AM - 03.00PM)</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="contact-wrapper">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="contact-img">
                                <img src="{% static 'school/images/01_1.jpg' %}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-7 align-self-center">
                            <div class="contact-form">
                                <div class="contact-form-header">
                                    <h2>Get In Touch</h2>
                                    <p>It is a long established fact that a reader will be distracted by the readable
                                        content of a page randomised words which don't look even slightly when looking at its layout. </p>
                                </div>
                                <form method="post"  id="contact-form">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <!-- <input type="text" class="form-control" name="name" placeholder="Your Name" required=""> -->
                                            {{form.name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="subject" placeholder="Your Subject" required="">
                                    </div>
                                    <div class="form-group">
                                        <textarea name="message" cols="30" rows="5" class="form-control" placeholder="Write Your Message"></textarea>
                                    </div>
                                    <button type="submit" class="theme-btn">Send
                                        Message <i class="far fa-paper-plane"></i></button>
                                    <div class="col-md-12 mt-3">
                                        <div class="form-messege text-success"></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end contact area -->

        <!-- map -->
        <div class="contact-map">
            <!-- <iframe src="https://www.google.com/maps/place/Little+Star+Public+School/@28.6877265,77.174921,11z/data=!4m10!1m2!2m1!1sLittle+Star+Public+School!3m6!1s0x390cf3806970e51d:0x54cb28c49cd774d2!8m2!3d28.6877293!4d77.4797896!15sChlMaXR0bGUgU3RhciBQdWJsaWMgU2Nob29skgEYZ2VuZXJhbF9lZHVjYXRpb25fc2Nob29sqgFhEAEqHSIZbGl0dGxlIHN0YXIgcHVibGljIHNjaG9vbCgAMh8QASIbhTwyG3AgNUSufih_aSvIhDDt0DFe-XRxYX6sMh0QAiIZbGl0dGxlIHN0YXIgcHVibGljIHNjaG9vbOABAA!16s%2Fg%2F11h9bfv91f?entry=ttu&g_ep=EgoyMDI1MDQzMC4xIKXMDSoASAFQAw%3D%3D" style="border:0;" allowfullscreen="" loading="lazy"></iframe> -->
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d224004.1079508996!2d77.17492103576666!3d28.68772648764515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cf3806970e51d%3A0x54cb28c49cd774d2!2sLittle%20Star%20Public%20School!5e0!3m2!1sen!2sin!4v1746515007568!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

        {% endblock %}

templates/web/gallery.html
{% extends "web/basic.html" %}
{% load static %}
{% block style %}

{% endblock %}
{% block content %}

        <!-- breadcrumb -->
        <div class="site-breadcrumb" style="background: url({% static 'school/images/01.jpg' %})">
            <div class="container">
                <h2 class="breadcrumb-title">Gallery</h2>
                <ul class="breadcrumb-menu">
                    <li><a href="{% url 'web:index' %}">Home</a></li>
                    <li class="active">Gallery</li>
                </ul>
            </div>
        </div>
        <!-- breadcrumb end -->


        {% if gallery %}
        <!-- gallery-area -->
        <div class="gallery-area py-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mx-auto">
                        <div class="site-heading text-center">
                            <span class="site-title-tagline"><i class="far fa-book-open-reader"></i> Gallery</span>
                            <h2 class="site-title">Our Photo <span>Gallery</span></h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of
                                a page when looking at its layout.</p>
                        </div>
                    </div>
                </div>
                <div class="row popup-gallery">
                    {% for group in gallery %}
                    <div class="col-md-4 wow fadeInUp" data-wow-delay=".25s">
                        {% for i in group %}
                        <div class="gallery-item">
                            <div class="gallery-img">
                                <img src="{{i.image.url}}" alt="">
                            </div>
                            <div class="gallery-content">
                                <a class="popup-img gallery-link" href="{{i.image.url}}"><i class="fal fa-plus"></i></a>
                            </div>
                        </div>
                        {% endfor %}

                       
                    </div>
                    {% endfor %}


                   
                </div>
            </div>
        </div>
        <!-- gallery-area end -->
         {% endif %}

        {% endblock %}

templates/web/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>School Website 2025</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600;800&display=swap" rel="stylesheet">
  <style>

* { box-sizing: border-box; margin: 0; padding: 0; }
    body, html {
      font-family: 'Inter', sans-serif;
      height: 100%;
    }

    .banner-slider {
      position: relative;
      width: 100%;
      height: 100%;
      overflow: hidden;
    }

    .slides {
      display: flex;
      width: 100%;
      height: 100%;
      transition: transform 1s ease;
    }

    .slide {
      width: 100%;
      height: 100%;
      flex-shrink: 0;
    }

    .slide img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .header-2025 {
      position: absolute;
      top: 2rem;
      left: 50%;
      transform: translateX(-50%);
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 1.2rem 2.5rem;
      background: rgba(255, 255, 255, 0.7);
      box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.10);
      backdrop-filter: blur(12px);
      border-radius: 1.5rem;
      max-width: 1100px;
      width: calc(100% - 4rem);
      z-index: 10;
    }

    .logo-2025 {
      display: flex;
      align-items: center;
      gap: 0.7rem;
      font-size: 1.7rem;
      font-weight: 800;
      color: #1a237e;
    }

    .logo-2025 img {
      width: 38px;
      height: 38px;
    }

    .nav-2025 {
      display: flex;
      gap: 2.5rem;
    }

    .nav-2025 a {
      text-decoration: none;
      color: #1a237e;
      font-weight: 600;
      font-size: 1.1rem;
      padding: 0.5rem 1.2rem;
      border-radius: 1.2rem;
      transition: background 0.2s, color 0.2s;
    }

    .nav-2025 a:hover {
      background: #5c6bc0;
      color: white;
    }

    /* Responsive menu toggle (same as before) */
    .menu-toggle { display: none; }
    .menu-icon { display: none; }

    @media (max-width: 800px) {
      .nav-2025 {
        position: absolute;
        top: 100%;
        right: 1.2rem;
        background: rgba(255, 255, 255, 0.95);
        border-radius: 1.2rem;
        flex-direction: column;
        gap: 0;
        width: 210px;
        padding: 1.2rem 0;
        opacity: 0;
        pointer-events: none;
        transform: translateY(-10px);
        transition: all 0.3s;
      }

      .nav-2025 a {
        width: 100%;
        padding: 1rem 2rem;
        border-radius: 0;
        font-size: 1.08rem;
      }

      .menu-icon {
        display: flex;
        flex-direction: column;
        cursor: pointer;
        width: 32px;
        height: 32px;
        justify-content: center;
        gap: 6px;
        z-index: 10;
      }

      .menu-icon span {
        display: block;
        height: 4px;
        width: 100%;
        background: #1a237e;
        border-radius: 2px;
        transition: 0.3s;
      }

      .menu-toggle:checked + .menu-icon span:nth-child(1) {
        transform: translateY(10px) rotate(45deg);
      }

      .menu-toggle:checked + .menu-icon span:nth-child(2) {
        opacity: 0;
      }

      .menu-toggle:checked + .menu-icon span:nth-child(3) {
        transform: translateY(-10px) rotate(-45deg);
      }

      .menu-toggle:checked ~ .nav-2025 {
        opacity: 1;
        pointer-events: auto;
        transform: translateY(0);
      }
    }
  </style>
</head>
<body>
  <div class="banner-slider">
    <div class="slides" id="slider">
      <div class="slide"><img src="/projects/school/assets/school/images/banner_1.jpeg" alt="Slide 1" style="height: 500px;width: 100%;"/></div>
      <div class="slide"><img src="https://source.unsplash.com/1600x900/?school,2" alt="Slide 2" /></div>
      <div class="slide"><img src="https://source.unsplash.com/1600x900/?school,3" alt="Slide 3" /></div>
    </div>
  
    <header class="header-2025">
      <div class="logo-2025">
        <img src="https://img.icons8.com/ios-filled/50/1a237e/school.png" alt="School Logo" />
        <span>SchoolName</span>
      </div>
      <input type="checkbox" id="menu-toggle" class="menu-toggle" />
      <label for="menu-toggle" class="menu-icon">
        <span></span>
        <span></span>
        <span></span>
      </label>
      <nav class="nav-2025">
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Admissions</a>
        <a href="#">Contact</a>
      </nav>
    </header>
  </div>
  
  <script>
    // Auto-slide every 4 seconds
    const slider = document.getElementById('slider');
    let index = 0;
  
    setInterval(() => {
      index = (index + 1) % 3; // number of slides
      slider.style.transform = `translateX(-${index * 100}%)`;
    }, 4000);
  </script>
  
</body>
</html>

templates/web/new1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sticky Glassmorphism Header 2025</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600;800&display=swap" rel="stylesheet">
  <style>
    body {
      margin: 0;
      font-family: 'Inter', Arial, sans-serif;
      min-height: 200vh;
      /* background: linear-gradient(120deg, #e0e7ff 0%, #f0fdfa 100%); */
    }
    .glass-header {
      position: sticky;
      top: 0;
      z-index: 100;
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 1.1rem 2.2rem;
      background: rgba(255, 255, 255, 0.55);
      box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.13);
      backdrop-filter: blur(18px) saturate(1.5);
      border-bottom: 1.5px solid #e0e7ff;
      transition: background 0.3s;
    }
    .logo-glass {
      display: flex;
      align-items: center;
      gap: 0.8rem;
      font-size: 1.5rem;
      font-weight: 800;
      color: #3730a3;
      letter-spacing: 1px;
      user-select: none;
    }
    .logo-glass img {
      width: 32px;
      height: 32px;
      display: block;
    }
    .nav-glass {
      display: flex;
      gap: 2.2rem;
      align-items: center;
    }
    .nav-glass a {
      text-decoration: none;
      color: #3730a3;
      font-weight: 600;
      font-size: 1.08rem;
      position: relative;
      padding: 0.5rem 0;
      transition: color 0.2s;
    }
    .nav-glass a::after {
      content: '';
      display: block;
      position: absolute;
      left: 50%;
      bottom: 0;
      width: 0%;
      height: 3px;
      background: linear-gradient(90deg, #6366f1 0%, #06b6d4 100%);
      border-radius: 2px;
      box-shadow: 0 0 8px #6366f1aa, 0 0 16px #06b6d488;
      transform: translateX(-50%);
      transition: width 0.3s;
    }
    .nav-glass a:hover {
      color: #06b6d4;
    }
    .nav-glass a:hover::after {
      width: 100%;
    }
    .menu-toggle-glass {
      display: none;
    }
    .menu-icon-glass {
      display: none;
      flex-direction: column;
      cursor: pointer;
      width: 36px;
      height: 36px;
      justify-content: center;
      align-items: center;
      z-index: 10;
    }
    .menu-icon-glass span {
      display: block;
      height: 4px;
      width: 32px;
      background: #6366f1;
      border-radius: 2px;
      margin: 4px 0;
      transition: 0.4s cubic-bezier(.68,-0.55,.27,1.55);
      position: relative;
    }
    /* Responsive styles */
    @media (max-width: 900px) {
      .glass-header {
        padding: 1rem 1.1rem;
      }
    }
    @media (max-width: 800px) {
      .nav-glass {
        position: absolute;
        top: 100%;
        right: 1.1rem;
        background: rgba(255,255,255,0.95);
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.10);
        border-radius: 1.5rem;
        flex-direction: column;
        align-items: flex-start;
        gap: 0;
        width: 210px;
        padding: 1.2rem 0;
        opacity: 0;
        pointer-events: none;
        transform: translateY(-10px);
        transition: all 0.3s;
      }
      .nav-glass a {
        width: 100%;
        padding: 1rem 2rem;
        border-radius: 0;
        font-size: 1.08rem;
      }
      .menu-icon-glass {
        display: flex;
      }
      /* Hamburger animation */
      .menu-toggle-glass:checked + .menu-icon-glass span:nth-child(1) {
        transform: translateY(8px) rotate(45deg);
      }
      .menu-toggle-glass:checked + .menu-icon-glass span:nth-child(2) {
        opacity: 0;
        transform: scaleX(0.5);
      }
      .menu-toggle-glass:checked + .menu-icon-glass span:nth-child(3) {
        transform: translateY(-8px) rotate(-45deg);
      }
      .menu-toggle-glass:checked ~ .nav-glass {
        opacity: 1;
        pointer-events: auto;
        transform: translateY(0);
      }
    }
  </style>
</head>
<body>
  <header class="glass-header">
    <div class="logo-glass">
      <img src="https://img.icons8.com/ios-filled/50/6366f1/school.png" alt="School Logo" />
      <span>SchoolName</span>
    </div>
    <input type="checkbox" id="menu-toggle-glass" class="menu-toggle-glass" />
    <label for="menu-toggle-glass" class="menu-icon-glass" aria-label="Open menu">
      <span></span>
      <span></span>
      <span></span>
    </label>
    <nav class="nav-glass">
      <a href="#">Home</a>
      <a href="#">About</a>
      <a href="#">Programs</a>
      <a href="#">Admissions</a>
      <a href="#">Contact</a>
    </nav>
  </header>
  <main style="padding:2rem;max-width:700px;margin:auto;">
    <h1>Welcome to SchoolName</h1>
    <p>Scroll down to see the sticky glassmorphism header in action. This header stays at the top, blurs the background, and features a glowing underline on navigation hover.</p>
    <p style="margin-top:3rem;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod, nisi eu consectetur consectetur, nisl nisi consectetur nisi, eu consectetur nisl nisi euismod nisi. (Add more content to test stickiness.)</p>
  </main>
</body>
</html>