customadmin/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='home'),
    path('event/', views.event, name='enent'),
    path('add-event/', views.add_event, name='add_event'),
    path('update-event/<int:id>/', views.add_event, name='update_event'),
    path('delete-event/<int:id>/', views.delete_event, name='delete_event'),
    path('gallery/', views.gallery, name='gallery'),
    path('add-gallery/', views.add_gallery, name='add_gallery'),
    path('update-gallery/<int:id>/', views.add_gallery, name='update_gallery'),
    path('delete-gallery/<int:id>/', views.delete_gallery, name='delete_gallery'),
    path('course/', views.course, name='course'),
    path('add-course/', views.add_course, name='add_course'),
    path('update-course/<int:id>/', views.add_course, name='update_course'),
    path('delete-course/<int:id>/', views.delete_course, name='delete_course'),
    path('contactus/', views.contactus, name='contactus'),
    path('view-contactus/<int:id>/', views.view_contactus, name='view_contactus'),
    path('delete-contactus/<int:id>/', views.delete_contactus, name='delete_contactus'),
    path('calendar_events/', views.calendar_events, name='calendar_events'),
    path('notice/', views.notice, name='notice'),
    path('add-notice/', views.add_notice, name='add_notice'),
    path('update-notice/<int:id>/', views.add_notice, name='update_notice'),
    path('delete-notice/<int:id>/', views.delete_notice, name='delete_notice'),
]

school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('admin/',include(('customadmin.urls','customadmin'),namespace='customadmin')),
    path('web/',include(('website.urls','website'),namespace='web')),
    path('',include(('website2.urls','website2'),namespace='web2')),
    path('user/',include(('users.urls','user'),namespace='user')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.loginPage, name='login'),
    path('logout/',views.logout_view,name='logout'),

]

customadmin/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError

# Create your models here.

class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True,blank=True)

    def __str__(self):
        return self.name
    
def validate_mp4(file):
    if not file.name.endswith('.mp4'):
        raise ValidationError("Only MP4 files are allowed.")

class Gallery(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='gallery_images/',blank=True,null=True)
    video = models.FileField(upload_to='gallery_video/',validators=[validate_mp4],blank=True,null=True)
    description = models.TextField(blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Contactus(models.Model):
    student_name = models.CharField(max_length=255)
    parents_name = models.CharField(max_length=255)
    parents_mobile_number = models.CharField(max_length=10)
    child_date_of_birth = models.DateField(null=True,blank=True)
    select_class_looking_for  = models.CharField(choices=[('P.Nursery','P.Nursery'),('Nursery','Nursery'),('LKG','LKG'),('UKG','UKG'),('1ST','1ST'),('2ND','2ND'),('3RD','3RD'),('4TH','4TH'),('5TH','5TH')])

    def __str__(self):
        return self.name

class Notice(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    file = models.FileField(upload_to='notices/', blank=True, null=True)

    class Meta:
        ordering = ['-date']
        verbose_name = "Notice"
        verbose_name_plural = "Notices"

    def __str__(self):
        return self.title
      

class Course(models.Model):
    title = models.CharField(max_length=200)
    description = RichTextField()
    fees = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='course_images/', null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

customadmin/forms.py
from django import forms
from users.models import CustomUser
from django.forms import EmailInput
from django.forms import ModelForm, TextInput, EmailInput, CharField, PasswordInput, ChoiceField, BooleanField, \
    NumberInput, DateInput
from .models import Event,Gallery,Contactus,Course,Notice
from ckeditor.widgets import CKEditorWidget
from datetime import date, timedelta
from django.core.exceptions import ValidationError


class EventForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['description'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['start_date'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['end_date'].widget.attrs.update({'class': 'form-control valid'})
        
        
    class Meta:
            model = Event
            fields = ('name','description','start_date','end_date')
            widgets = {
            'start_date':DateInput(attrs={
                'type': 'date',
                'class': "form-control mb-2",}),
             'end_date':DateInput(attrs={
                'type': 'date',
                'class': "form-control mb-2",
                'placeholder':"date hai"}),
                }


class GalleryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['image'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['description'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['video'].widget.attrs.update({'class': 'form-control valid','multiple':True})
        
        
    class Meta:
            model = Gallery
            fields = ('title','image','description','video')
            widgets = {

            'image': forms.ClearableFileInput(attrs={'allow_multiple_selected': True}),
            'video': forms.ClearableFileInput(attrs={'allow_multiple_selected': True})

            }

    def clean_Video(self):
        video = self.cleaned_data.get('Video')
        if video and not video.name.endswith('.mp4'):
            raise forms.ValidationError("Only MP4 files are allowed.")
        return video
           


class ContactusForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student_name'].widget.attrs.update({'class': 'form-control valid','placeholder':'Student Name'})
        self.fields['parents_name'].widget.attrs.update({'class': 'form-control valid','placeholder':'Parents Name'})
        self.fields['parents_mobile_number'].widget.attrs.update({'class': 'form-control valid','placeholder':'Parents Mobile Number'})
        self.fields['child_date_of_birth'].widget.attrs.update({'class': 'form-control valid','placeholder':'Child Date Of Birth'})
        self.fields['select_class_looking_for'].widget.attrs.update({'class': 'form-control valid','placeholder':'Select Class Looking For'})
        
        
    class Meta:
            model = Contactus
            fields = ('student_name','parents_name','parents_mobile_number','child_date_of_birth','select_class_looking_for')
            widgets = {
            'child_date_of_birth':DateInput(attrs={
                'type': 'date',
                'class': "form-control mb-2",
                'placeholder': 'Enter Child Date of Birth',}),}
    child_date_of_birth = forms.DateField(
        input_formats=['%d-%m-%Y'],
        widget=forms.TextInput(attrs={
            'type': 'text',
            'class': 'form-control valid',
            'placeholder': 'Enter Child Date of Birth'
        })
    )
    def clean_child_date_of_birth(self):
        dob = self.cleaned_data.get('child_date_of_birth')
        if dob:
            today = date.today()
            min_age_date = today - timedelta(days=2.5 * 365.25)  # 2.5 years as days
            if dob > min_age_date:
                raise ValidationError("Child must be at least 2.5 years old.")
        return dob
            


class CourseForm(ModelForm):
    description = forms.CharField(widget=CKEditorWidget()) 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control valid','placeholder':'Your Name'})
        self.fields['fees'].widget.attrs.update({'class': 'form-control valid','placeholder':'Your Email'})
        self.fields['image'].widget.attrs.update({'class': 'form-control valid','placeholder':'Your Subject'})
        self.fields['description'].widget.attrs.update({'class': 'form-control valid','placeholder':'Write your message'})
        
        
    class Meta:
            model = Course
            fields = ('title','fees','image','description')

class NoticeForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['description'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['date'].widget.attrs.update({'class': 'form-control valid'})
        self.fields['file'].widget.attrs.update({'class': 'form-control valid'})
        
        
    class Meta:
            model = Notice
            fields = ('title','description','date','file')
            widgets = {
            'date':DateInput(attrs={
                'type': 'date',
                'class': "form-control mb-2",
                'placeholder': 'Enter Child Date of Birth',}),}

customadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from .models import Event,Gallery,Contactus,Course,Notice
from .forms import EventForm,GalleryForm,ContactusForm,CourseForm,NoticeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_GET

# Create your views here.
def index(request):
    return render(request,'customadmin/index.html')

def event(request):
    event = Event.objects.all()
    return render(request,'customadmin/eventlist.html',{'event':event})

def add_event(request,id=None):
    print('run')
    if request.method == "POST":
        print('post')
        print(request.POST)
        obj=None
        if id:
            obj = get_object_or_404(Event, id=id)
            form = EventForm(request.POST,instance=obj)
        else:
            form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            
            messages.success(request, f'Event has been Added successfully!')
            return redirect('customadmin:enent')
        else:
            print('errr',form.errors)
            
            messages.error(request, f'{form.errors}')
    else:
        obj=None
        if id:
            obj = get_object_or_404(Event, id=id)
            form = EventForm(instance=obj)
        else:
            form = EventForm()
    
    return render(request, 'customadmin/event_add.html', {'form': form,'obj':obj})

def delete_event(request,id=None):
    if id:
        obj = get_object_or_404(Event, id=id)
        obj.delete()
        
        messages.success(request, f'Event has been removed successfully!')
        return redirect('customadmin:enent')
  
  
def gallery(request):
    gallery = Gallery.objects.all()
    return render(request,'customadmin/gallery.html',{'gallery':gallery})

def add_gallery(request,id=None):
    print('run')
    if request.method == "POST":
        print('post')
        print(request.POST)
        obj=None
        if id:
            obj = get_object_or_404(Gallery, id=id)
            print('data:',obj)
            form = GalleryForm(request.POST,request.FILES,instance=obj)
        else:
            form = GalleryForm(request.POST,request.FILES)
        if form.is_valid():
            images = request.FILES.getlist('image')
            videos = request.FILES.getlist('video')
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            if images:
                for img in images:
                    Gallery.objects.create(title=title,description=description,image=img)
            if videos:
                for vid in videos:
                    Gallery.objects.create(title=title,description=description,video=vid)

            # form.save()
            
            messages.success(request, f'Gallery been updated successfully!')
            return redirect('customadmin:gallery')
        else:
            print('errr',form.errors)
            
            messages.error(request, f'{form.errors}')
    else:
        obj=None
        print(id)
        if id:
            obj = get_object_or_404(Gallery, id=id)
            print
            form = GalleryForm(instance=obj)
        else:
            form = GalleryForm()
    
    return render(request, 'customadmin/gallery_add.html', {'form': form,'obj':obj})

def delete_gallery(request,id=None):
    if id:
        obj = get_object_or_404(Gallery, id=id)
        obj.delete()
        
        messages.success(request, f'Gallery has been removed successfully!')
        return redirect('customadmin:gallery')
  
def contactus(request):
    contactus = Contactus.objects.all().order_by("-id")
    return render(request,'customadmin/contact.html',{'contactus':contactus})


def delete_contactus(request,id=None):
    if id:
        obj = get_object_or_404(Contactus, id=id)
        obj.delete()
        
        messages.success(request, f'Contact has been removed successfully!')
        return redirect('customadmin:contactus')
    
def view_contactus(request,id=None):
    # print('run')
    form=None
    # print(id)
    if id:
        obj = get_object_or_404(Contactus, id=id)
        form = ContactusForm(instance=obj)
    return render(request, 'customadmin/contact_view.html', {'form': form,'obj':obj})


def course(request):
    course = Course.objects.all()
    return render(request,'customadmin/course.html',{'course':course})

def add_course(request,id=None):
    print('run')
    if request.method == "POST":
        print('post')
        print(request.POST)
        obj=None
        if id:
            obj = get_object_or_404(Course, id=id)
            print('data:',obj)
            form = CourseForm(request.POST,request.FILES,instance=obj)
        else:
            form = CourseForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            
            messages.success(request, f'Course been updated successfully!')
            return redirect('customadmin:course')
        else:
            print('errr',form.errors)
            
            messages.error(request, f'{form.errors}')
    else:
        obj=None
        print(id)
        if id:
            obj = get_object_or_404(Course, id=id)
         
            form = CourseForm(instance=obj)
        else:
            form = CourseForm()
    
    return render(request, 'customadmin/course_add.html', {'form': form,'obj':obj})

def delete_course(request,id=None):
    if id:
        obj = get_object_or_404(Course, id=id)
        obj.delete()
        
        messages.success(request, f'Course has been removed successfully!')
        return redirect('customadmin:course')


def calendar_events(request):
    month = int(request.GET.get("month", 1))
    year = int(request.GET.get("year", 2025))
    
    events = Event.objects.filter(start_date__year=year, start_date__month=month).values('start_date','name','description')
    return JsonResponse(list(events), safe=False)




def notice(request):
    notice = Notice.objects.all()
    return render(request,'customadmin/notice.html',{'notice':notice})

def add_notice(request,id=None):
    print('run')
    if request.method == "POST":
        print('post')
        print(request.POST)
        obj=None
        if id:
            obj = get_object_or_404(Notice, id=id)
            print('data:',obj)
            form = NoticeForm(request.POST,request.FILES,instance=obj)
        else:
            form = NoticeForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            
            messages.success(request, f'notice been updated successfully!')
            return redirect('customadmin:notice')
        else:
            print('errr',form.errors)
            
            messages.error(request, f'{form.errors}')
    else:
        obj=None
        print(id)
        if id:
            obj = get_object_or_404(Notice, id=id)
         
            form = NoticeForm(instance=obj)
        else:
            form = NoticeForm()
    
    return render(request, 'customadmin/notice_add.html', {'form': form,'obj':obj})

def delete_notice(request,id=None):
    if id:
        obj = get_object_or_404(Notice, id=id)
        obj.delete()
        
        messages.success(request, f'Notice has been removed successfully!')
        return redirect('customadmin:notice')

templates/customadmin/eventlist.html
{% extends 'customadmin/basic.html' %} 
{% load static %}
{% block style %}


    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/forms/select/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/responsive.bootstrap5.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/buttons.bootstrap5.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/rowGroup.bootstrap5.min.css' %}">
    <!-- END: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/menu/menu-types/vertical-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/form-validation.css' %}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!-- END: Custom CSS-->

{% endblock style %}
{% block content %}


    <!-- BEGIN: Content-->
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-xxl p-0">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <!-- users list start -->
                <section class="app-user-list">
                
                    <!-- list and filter start -->
                    <div class="card">
                        
                        <div class="card-body border-bottom">
                            <div class="row">
                                <div class="col-md-4 user_role">
                                    Events
                                </div>
                                <div class="col-md-6 user_plan">
                                </div>
                                <div class="col-md-2 user_status">
                                    <a href="{% url 'customadmin:add_event' %}"><button class="btn btn-primary w-80 waves-effect waves-float waves-light" >Add Event</button></a>
                                </div>
                            </div>
                        </div>
                        {% if event %}
                        <div class="card-datatable table-responsive pt-0">
                            <table class="user-list-table table">
                                <thead class="table-light">
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in event %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{i.name}}</td>
                                        <td>{{ i.description|truncatechars:25 }}</td>

                                        <td>
                                           <a href="{% url 'customadmin:update_event' id=i.id %}">
                                            <i data-feather="edit" class="text-primary w-60 waves-effect waves-float waves-light"></i>
 
                                            {% comment %} <button class="btn btn-primary w-60 waves-effect waves-float waves-light">View Details</button> {% endcomment %}
                                            </a>
                                            <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Show Attendance">

                                            <a href="{% url 'customadmin:delete_event' id=i.id %}">
                                              <i data-feather="trash" class="text-danger w-60 waves-effect waves-float waves-light"></i>

                                            </a>
                                          </span>
                                          {% comment %} {% if i.is_active == False %}
                                            <button class="btn btn-primary w-60 waves-effect waves-float waves-light" onclick="approved('{{ i.id }}','{{ i.first_name }}')">Approve</button>
                                          {% elif i.is_active == True %}
                                            <button class="btn btn-warning w-60 waves-effect waves-float waves-light" onclick="rejected_landload('{{ i.id }}','{{ i.first_name }}')">Reject</button>
                                          {% else %}
                                          <button class="btn btn-primary w-60 waves-effect waves-float waves-light" onclick="approved('{{ i.id }}','{{ i.first_name }}')">Approve</button>
                                          <button class="btn btn-warning w-60 waves-effect waves-float waves-light" onclick="rejected_landload('{{ i.id }}','{{ i.first_name }}')">Reject</button>
                                          {% endif %} {% endcomment %}
                                            <!-- <button onclick="deletelandload('{{ i.id }}','{{ i.first_name }}')">Delete</button> -->
                                        </td>
                                        
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}
                    </div>
                    <!-- list and filter end -->
                </section>
                <!-- users list ends -->

            </div>
        </div>
{% endblock content %}
{% block scriptjs %}




    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'app-assets/vendors/js/forms/select/select2.full.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/responsive.bootstrap5.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/datatables.buttons.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/jszip.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/pdfmake.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/vfs_fonts.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/buttons.html5.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/buttons.print.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.rowGroup.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/forms/validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/forms/cleave/cleave.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/forms/cleave/addons/cleave-phone.us.js' %}"></script>
    <!-- END: Page Vendor JS-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- BEGIN: Theme JS-->
    <script src="{% static 'app-assets/js/core/app-menu.js' %}"></script>
    <script src="{% static 'app-assets/js/core/app.js' %}"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <!-- <script src="{% static 'app-assets/js/scripts/pages/app-user-list.js' %}"></script> -->
    <!-- END: Page JS-->

<!-- END: Body-->
<!-- <script>
  document.getElementById('searchbtn001').addEventListener('click', function() {
      document.getElementById('search001').submit();
  });
</script> -->

<script>
    function approved(id,name) {
    var id =id
    var approveLandloadUrl='/landload/approve_landload/'+id
  Swal.fire({

      title: "Are you sure?",
      text: "You want to approve "+name,
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "Approved"
    }).then((result) => {
      if (result.isConfirmed) {
        var pk=id
        // If user confirms, make AJAX request to delete endpoint
        // Replace 'delete-url' with the actual URL to delete the item
        fetch(approveLandloadUrl, {  // Use template literal
          method: 'get',
          headers: {
            'Content-Type': 'application/json'
          }
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          // Handle success response
          Swal.fire({
            title: "Approved!",
            text: "Landload has been Approved.",
            icon: "success"
          }).then(() => {
                    // Reload the page after showing the alert
                    location.reload();
                });
        })
        .catch(error => {
          // Handle error
          console.error('Error Approved Landload:', error);
          Swal.fire({
            title: "Error",
            text: "Failed to Approved the Landload.",
            icon: "error"
          });
        });
      }
    });
}

function rejected_landload(id,name) {
    var id =id
    var rejectedLandloadUrl='/landload/reject_landload/'+id
  Swal.fire({

      title: "Are you sure?",
      text: "You want to reject "+name,
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "rejected"
    }).then((result) => {
      if (result.isConfirmed) {
        var pk=id
        // If user confirms, make AJAX request to delete endpoint
        // Replace 'delete-url' with the actual URL to delete the item
        fetch(rejectedLandloadUrl, {  // Use template literal
          method: 'get',
          headers: {
            'Content-Type': 'application/json'
          }
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          // Handle success response
          Swal.fire({
            title: "rejected!",
            text: "Landload has been rejected.",
            icon: "success"
          }).then(() => {
                    // Reload the page after showing the alert
                    location.reload();
                });
        })
        .catch(error => {
          // Handle error
          console.error('Error rejected Landload:', error);
          Swal.fire({
            title: "Error",
            text: "Failed to rejected the Landload.",
            icon: "error"
          });
        });
      }
    });
}

    /*=========================================================================================
    File Name: app-user-list.js
    Description: User List page
    --------------------------------------------------------------------------------------
    Item Name: Vuexy  - Vuejs, HTML & Laravel Admin Dashboard Template
    Author: PIXINVENT
    Author URL: http://www.themeforest.net/user/pixinvent

==========================================================================================*/
$(function () {
  ('use strict');

  var dtUserTable = $('.user-list-table'),
    newUserSidebar = $('.new-user-modal'),
    newUserForm = $('.add-new-user'),
    select = $('.select2'),
    dtContact = $('.dt-contact'),
    statusObj = {
      1: { title: 'Pending', class: 'badge-light-warning' },
      2: { title: 'Active', class: 'badge-light-success' },
      3: { title: 'Inactive', class: 'badge-light-secondary' }
    };

  var assetPath = "{% static 'app-assets/' %}",
    userView = 'app-user-view-account.html';

  if ($('body').attr('data-framework') === 'laravel') {
    assetPath = $('body').attr('data-asset-path');
    userView = assetPath + 'app/user/view/account';
  }

  select.each(function () {
    var $this = $(this);
    $this.wrap('<div class="position-relative"></div>');
    $this.select2({
      // the following code is used to disable x-scrollbar when click in select input and
      // take 100% width in responsive also
      dropdownAutoWidth: true,
      width: '100%',
      dropdownParent: $this.parent()
    });
  });

  // Users List datatable
  
  // Form Validation
  if (newUserForm.length) {
    newUserForm.validate({
      errorClass: 'error',
      rules: {
        'user-fullname': {
          required: true
        },
        'user-name': {
          required: true
        },
        'user-email': {
          required: true
        }
      }
    });

    newUserForm.on('submit', function (e) {
      var isValid = newUserForm.valid();
      e.preventDefault();
      if (isValid) {
        newUserSidebar.modal('hide');
      }
    });
  }

  // Phone Number
  if (dtContact.length) {
    dtContact.each(function () {
      new Cleave($(this), {
        phone: true,
        phoneRegionCode: 'US'
      });
    });
  }
});
</script>

{% endblock scriptjs %}
</html>